spring.application.name=c-music
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASS}

management.endpoints.web.exposure.include=mappings
logging.level.org.hibernate.SQL=DEBUG
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true